export const GET_USER_REQUESTED = 'GET_USER_REQUESTED';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_FAILED = 'GET_USER_FAILED';

export const CREATE_USER_REQUESTED = 'CREATE_USER_REQUESTED';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_FAILED = 'CREATE_USER_FAILED';

export const LISTEN_USER_REQUESTED = 'LISTEN_USER_REQUESTED';
export const LISTEN_USER_SUCCESS = 'LISTEN_USER_SUCCESS';
export const LISTEN_USER_FAILED = 'LISTEN_USER_FAILED';

export const LOGIN_USER_REQUESTED = 'LOGIN_USER_REQUESTED';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILED = 'LOGIN_USER_FAILED';

export const TOGGLE_DRAWER = 'TOGGLE_DRAWER';
